Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2023-09, with the labels that each got.

#94 Adjust Proj0004 to solve issue of NugetAudit being broken for the .NET 7 SDK
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Run_NuGet_security_audits_automatically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs
Labels: FP

#95 Use PolySharp
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#96 Fix Proj0018 always triggering
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Order_using_directives_by_type.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/CheckOrderExtensions.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesByType.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: bug, FP

#97 Support Directory.Build.props
  dotnet-project-file-analyzers.sln
  projects/WithDirectoryBuildProps/Directory.Build.props
  projects/WithDirectoryBuildProps/Placeholder.cs
  projects/WithDirectoryBuildProps/WithDirectoryBuildProps.csproj
  specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Directory_Build_props_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Add_additional_files.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.IO.FileSystemInfo.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
Labels: enhancement
