Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2023-08, with the labels that each got.

#82 FP Proj0202: Support both <Description> and <PackageDescription>
  dotnet-project-file-analyzers.sln
  projects/PackageDescription/PackageDescription.csproj
  projects/PackageDescription/Placeholder.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_info.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Nodes.T.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Nodes.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageDescription.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: FP

#83 Downgrade version Roslyn dependency
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: bug, enhancement

#84 Add using analyzers
  dotnet-project-file-analyzers.sln
  projects/IncorrectlyOrderedUsingDirectives/IncorrectlyOrderedUsingDirectives.csproj
  projects/IncorrectlyOrderedUsingDirectives/Palceholder.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/Issue.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Order_using_directives_by_type.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Order_using_directives_in_alphabetical_order.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Static_alias_using_not_supported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/CheckOrderExtensions.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesByType.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/StaticAliasUsingNotSupported.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Using.cs
  src/DotNetProjectFile.Analyzers/MsBuild/UsingType.cs
  src/DotNetProjectFile.Analyzers/Properties/GlobalUsings.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#87 Suppress dependencies when packing
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#90 FN & FP: Fix sorting check
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/IO/File_path_compare.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/IO/FilePathComparer.cs
Labels: FN, FP

#89 New Rule Proj1100: Avoid using Moq
  dotnet-project-file-analyzers.sln
  projects/UsesMoq/Placeholder.cs
  projects/UsesMoq/UsesMoq.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Avoid_using_Moq.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidUsingMoq.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#92 FP/FN: Sorting of referencese should be case insensitive
  specs/DotNetProjectFile.Analyzers.Specs/IO/File_path_compare.cs
  specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Choose_specs.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/IO/FilePathComparer.cs
Labels: bug, FN, FP

#88 New Rule Proj1200: Exclude private assets as project file dependency
  dotnet-project-file-analyzers.sln
  projects/PrivateAssets/Placeholder.cs
  projects/PrivateAssets/PrivateAssets.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Exclude_private_asset_dependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/InheritableAttribute.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
  src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs
  src/DotNetProjectFile.Analyzers/NuGet/Package.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: help wanted, New rule
