Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2024-09, with the labels that each got.

#153 Proj0804: Only use Version when CPM is not enabled]
  projects/MisuseVersion/Directory.Packages.props
  projects/MisuseVersion/MisuseVersion.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_VersionOverride_only_with_CPM.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_Version_only_without_CPM.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseVersionOnlyWithoutCpm.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#155 Proj0806: VersionOverride should change the version
  projects/VersionUpdateNotDifferent/Directory.Packages.props
  projects/VersionUpdateNotDifferent/VersionUpdateNotDifferent.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/VersionOverride_should_change_version.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/VersionOverrideShouldChangeVersion.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#160 Do not check for unstable versions in <PackageVersion> but at the loc…
  projects/UnstableVersionsCPM/Directory.Packages.props
  projects/UnstableVersionsCPM/UnstableVersionsCPM.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Package_references_should_be_stable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
Labels: FP

#161 Proj0805: could not resolve package versions in props file
  projects/PackageReferenceWithoutVersion/Directory.Packages.props
  projects/PackageReferenceWithoutVersion/PackageReferenceWithoutVersion.csproj
  projects/PackageReferenceWithoutVersion/common.props
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Define_package_reference_version.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionIncludeShouldExist.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
Labels: FP

#162 Proj1702: Omit XML declarations
  projects/XmlDeclaration/XmlDeclaration.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Ommit_XML_declaration.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#163 Remove XML declarations from test props files
  projects/BloatedDirectoryPackagesProps/Directory.Packages.props
  projects/EnableCPMLocally/Directory.Packages.props
  projects/MisuseVersion/Directory.Packages.props
  projects/TargetFrameworksSingleWithBase/common.props
  projects/UnstableVersionsCPM/Directory.Packages.props
  projects/UseCPM/Directory.Packages.props
  projects/VersionUpdateNotDifferent/Directory.Packages.props
  projects/props/DoublePackageReferences.props
  projects/props/common.props
  projects/props/common1.props
  projects/props/common2.props
  projects/props/simple.props
  props/common.props
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Use_Directory_Packages_props_only_for_CPM.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Include_package_references_once.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Reassign_properties_with_different_value.cs
Labels: enhancement

#164 Proj1200: Microsoft.NET.Test.Sdk should be considered a private asset
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Labels: FN

#165 Add 47 more private assets
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
  src/DotNetProjectFile.Analyzers/NuGet/SourceGenerator.cs
Labels: enhancement

#166 Fix old urls in package info
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: documentation

#171 Enable own analyzer for specs project
  props/common.props
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#173 Explicit usings for Specs project
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/IssueComparer.cs
  specs/DotNetProjectFile.Analyzers.Specs/Properties/GlobalUsings.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/All.cs
Labels: enhancement

#172 <IsTestProject> is true ensure Proj0200 and Proj0400 do not report
  projects/TestProject/TestProject.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_is_packable.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_is_publishable.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_info.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseDirectoryPackagesPropsOnlyForCPM.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.MsBuild.Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/IsTestProject.cs
  src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
Labels: FP

#178 Proj0452 & Proj0453: Microsoft.NET.Test.Sdk and IsTestProject should tell the same story
  projects/TestProjectWithoutSdk/TestProjectWithoutSdk.csproj
  projects/TestSdkOnly/TestSdkOnly.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Require_SDK.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_packable.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_publishable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#180 Proj0215: Provide a compliant NuGet package icon
  design/logo_400x400.png
  projects/BigIcon/BigIcon.csproj
  projects/BmpIcon/BmpIcon.csproj
  projects/BmpIcon/big-icon.bmp
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Avoid_license_url.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Define_is_packable.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Define_package_info.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Package_icon.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_forward_slashes_in_paths.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProvideCompliantPackageIcon.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/System.IO.BinaryReader.cs
  src/DotNetProjectFile.Analyzers/IO/IOFile.cs
  src/DotNetProjectFile.Analyzers/IO/ImageInfo.cs
  src/DotNetProjectFile.Analyzers/MsBuild/BuildAction.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#183 Introduction of case-insensitive string.IsMatch(string?)
  dictionary.dic
  specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Indent_RESX.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidUsingMoq.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.String.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
  src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs
  src/DotNetProjectFile.Analyzers/Resx/Resources.cs
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: enhancement

#181 FP Proj2100: Space preserved closing nodes should not be reported
  projects/FaultyIndenting/FaultyIndenting.resx
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/System.Xml.Linq.XElement.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/Resx/Node.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs
Labels: FP

#182 Proj0026: Remove IncludeAssets when redundant
  projects/CompliantCSharp/CompliantCSharp.csproj
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  projects/IncludeAssets/IncludeAssets.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_IncludeAssets_when_redundant.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveIncludeAssetsWhenRedundant.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/System.String.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#186 Proj0028: Define conditions on level 1
  projects/Conditional/Conditional.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_conditions_on_level_1.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineConditionsOnLevel1.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Otherwise.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#190 Disable Proj1100: Avoid using Moq
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: FP

#191 Time reduction for querying typed nodes
  specs/Benchmarks/Benchmarks.csproj
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectShouldNotBePackable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectShouldNotBePublishable.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ResourceFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.Xml.XmlAnalysisNode.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Nodes.T.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Nodes.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Otherwise.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
  src/DotNetProjectFile.Analyzers/Properties/GlobalUsings.cs
  src/DotNetProjectFile.Analyzers/Resx/Data.cs
  src/DotNetProjectFile.Analyzers/Resx/Node.cs
  src/DotNetProjectFile.Analyzers/Resx/Nodes.cs
  src/DotNetProjectFile.Analyzers/Resx/ResHeader.cs
  src/DotNetProjectFile.Analyzers/Resx/Resource.cs
  src/DotNetProjectFile.Analyzers/Xml/Nodes.T.cs
  src/DotNetProjectFile.Analyzers/Xml/Nodes.cs
Labels: enhancement

#193 Release v1.4.3
  analyzers-config.ini
  projects/SuppressIssues/SuppressIssues.csproj
  specs/Benchmarks/Benchmarks.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Warning_pragma_disable.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: enhancement

#195 Rules should only report on nodes defined in MS Build project file of current context
  specs/Benchmarks/README.md
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageReferencesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageVersionsAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderProjectReferencesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesByType.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/StaticAliasUsingNotSupported.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: bug

#196 Use walker to navigate to MS Build file tree
  projects/DoublePackageReferences/DoublePackageReferences.csproj
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/Issue.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/IssueComparer.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/All.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Define_package_reference_version.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Enable_CPM_globally.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Use_Directory_Packages_props_only_for_CPM.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Include_package_references_once.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Package_references_should_be_stable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidGeneratePackageOnBuildWhenNotPackable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionIncludeShouldExist.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineIsPackable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineIsPublishable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineOutputType.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageValidationBaselineVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludePackageReferencesOnce.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeProjectReferencesOnce.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OverrideTargetFrameworksWithTargetFrameworks.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProvideCompliantPackageIcon.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ReassignPropertiesWithDifferentValue.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/VersionOverrideShouldChangeVersion.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.MsBuild.Project.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.Array.cs
  src/DotNetProjectFile.Analyzers/IO/IOPath.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Conditions.cs
  src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.Property.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.Walk.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileType.cs
  src/DotNetProjectFile.Analyzers/Navigation/ProjectTrace.cs
  src/DotNetProjectFile.Analyzers/Properties/GlobalUsings.cs
  src/DotNetProjectFile.Analyzers/Rule.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs
Labels: enhancement

#197 Introduction of generic Grammar
  dictionary.dic
  specs/Benchmarks/Benchmarks.csproj
  specs/Benchmarks/Files/ini-0027-lines.ini
  specs/Benchmarks/Files/ini-0036-lines.ini
  specs/Benchmarks/Files/ini-1220-lines.ini
  specs/Benchmarks/IniFile.cs
  specs/Benchmarks/Program.cs
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/ParserAssertions.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/_should.cs
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/Grammar_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
  specs/DotNetProjectFile.Analyzers.Specs/TestTools/Source.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionsShouldHaveSingleTask.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProvideCompliantPackageIcon.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/Analyzers/ResourceFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.Collections.Immutable.ImmutableArray.cs
  src/DotNetProjectFile.Analyzers/IO/IODirectory.cs
  src/DotNetProjectFile.Analyzers/Ini/HeaderSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/IniFileSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/IniGrammar.cs
  src/DotNetProjectFile.Analyzers/Ini/IniSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/KeySyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/KeyValuePairSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/SectionSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/ValueSyntax.cs
  src/DotNetProjectFile.Analyzers/Parsing/Grammar.cs
  src/DotNetProjectFile.Analyzers/Parsing/Grammar.static.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/AddSyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/And.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/EndOfFile.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Lazy.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Matches.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Or.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/RegularExpression.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Repeat.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/StartWithChar.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/StartWithString.cs
  src/DotNetProjectFile.Analyzers/Parsing/Matching.cs
  src/DotNetProjectFile.Analyzers/Parsing/Parser.cs
  src/DotNetProjectFile.Analyzers/Properties/GlobalUsings.cs
  src/DotNetProjectFile.Analyzers/Syntax/CreateSyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Syntax/InvalidPattern.cs
  src/DotNetProjectFile.Analyzers/Syntax/RootSyntax.cs
  src/DotNetProjectFile.Analyzers/Syntax/SourceSpan.cs
  src/DotNetProjectFile.Analyzers/Syntax/SourceSpanToken.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Xml/Nodes.T.cs
  src/DotNetProjectFile.Analyzers/Xml/Nodes.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs
Labels: enhancement

#199 Improve on INI grammar
  specs/Benchmarks/IniFile.cs
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
  src/DotNetProjectFile.Analyzers/Collections/Slice.cs
  src/DotNetProjectFile.Analyzers/Collections/SliceSpan.cs
  src/DotNetProjectFile.Analyzers/Ini/HeaderSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/IniFileSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/KeySyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/KeyValuePairSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/SectionSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/ValueSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/_grammar.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.Property.cs
  src/DotNetProjectFile.Analyzers/Parsing/ParseBuffer.cs
  src/DotNetProjectFile.Analyzers/Parsing/Parser.cs
  src/DotNetProjectFile.Analyzers/Syntax/RootSyntax.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNodeCollection.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNodeResolver.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
Labels: enhancement

#200 Define file cache that is shared amongst all analyzers
  specs/Benchmarks/IniFile.cs
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/EmbedValidResourceFiles.cs
  src/DotNetProjectFile.Analyzers/Caching/CompilationCache.cs
  src/DotNetProjectFile.Analyzers/Caching/FileCache.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.IO.FileSystemInfo.cs
  src/DotNetProjectFile.Analyzers/IO/IODirectory.cs
  src/DotNetProjectFile.Analyzers/IO/IOFile.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Import.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
  src/DotNetProjectFile.Analyzers/Resx/Resource.cs
  src/DotNetProjectFile.Analyzers/Resx/Resources.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
Labels: enhancement

#204 Support rules on .editorconfig files
  .editorconfig
  dictionary.dic
  specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Warning_pragma.cs
  src/DotNetProjectFile.Analyzers/Analyzers/EditorConfigFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/Analyzers/ProjectFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/Locations.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/WarningPragma.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/WarningPragmas.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/EditorConfig/EditorConfigFile.cs
  src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.CodeAnalysis.ProjectFile.cs
  src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.Linq.Enumerable.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/Properties/GlobalUsings.cs
  src/DotNetProjectFile.Analyzers/Resx/Resource.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
Labels: enhancement

#207 Implement Glob expression parser
  specs/Benchmarks/Benchmarks.csproj
  specs/Benchmarks/Globs.cs
  specs/Benchmarks/Program.cs
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/IO/Glob_parse_specs.cs
  src/DotNetProjectFile.Analyzers/IO/Glob.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/AnyChar.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/GlobParser.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Group.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Literal.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/NotSequense.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Option.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/RecursiveWildcard.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Segement.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Sequence.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Wildcard.cs
  src/DotNetProjectFile.Analyzers/Syntax/SourceSpan.cs
Labels: enhancement
