Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2024-11, with the labels that each got.

#216 Fix FP on 2100
  projects/FaultyIndenting/FaultyIndenting.resx
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IndentXml.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/IndentResx.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: FP

#217 XML nodes within resource values should be escaped
  projects/ResxWithHtmlContent/Messages.resx
  projects/ResxWithHtmlContent/ResxWithHtmlContent.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Escape_XML_nodes_resource_values.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/EscapeXmlNodesResourceValues.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#219 Fix some small issues
  .editorconfig
  specs/Benchmarks/Benchmarks.csproj
  specs/Benchmarks/Files/ini-0036-lines.ini
  specs/Benchmarks/nuget.config
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  src/DotNetProjectFile.Analyzers/Parsing/Grammar.cs
  src/DotNetProjectFile.Analyzers/Parsing/Grammar.static.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
Labels: enhancement

#218 Fix RS1038 warning
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#223 New Rule: Use VB.NET specific properties only in when applicable
  dictionary.dic
  projects/VBOnlyProperties/Directory.Build.props
  projects/VBOnlyProperties/VBOnlyProperties.vbproj
  projects/VBOnlyPropertiesCSharp/Directory.Build.props
  projects/VBOnlyPropertiesCSharp/VBOnlyPropertiesCSharp.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_VB_specific_only_in_VB_context.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInVBContextOnly.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileTypes.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/FrameworkPathOverride.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/NoVBRuntimeReference.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/OptionExplicit.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/OptionInfer.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/OptionStrict.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/RemoveIntegerChecks.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/VbcToolPath.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VisualBasic/VbcVerbosity.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#224 Proj0029: Use C# specific properties only when applicable
  dictionary.dic
  projects/CSharpOnlyProperties/CSharpOnlyProperties.csproj
  projects/CSharpOnlyProperties/Directory.Build.props
  projects/CSharpOnlyPropertiesVB/CSharpOnlyPropertiesVB.vbproj
  projects/CSharpOnlyPropertiesVB/Directory.Build.props
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_CSharp_specific_only_in_CSharp_context.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_VB_specific_only_in_VB_context.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInCSharpContextOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInVBContextOnly.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/CSharp/AllowUnsafeBlocks.cs
  src/DotNetProjectFile.Analyzers/MsBuild/CSharp/CheckForOverflowUnderflow.cs
  src/DotNetProjectFile.Analyzers/MsBuild/CSharp/Nullable.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#228 Proj0031: Adopt preferred casing of nodes
  dictionary.dic
  projects/CaseInsensitive/CaseInsensitive.csproj
  projects/CaseInsensitive/Extra.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Adopt_preferred_casing.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AdoptPreferredCasing.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/System.Xml.Linq.XElement.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/MsBuild/NodeFactory.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#229 Support Directory.Build.targets
  projects/WithDirectoryBuildProps/Directory.Build.targets
  specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Directory_Build_props_specs.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
Labels: enhancement

#233 Update to .NET 9.0
  .github/workflows/build-test.yaml
  projects/WithPackageProps/WithPackageProps.csproj
  props/common.props
  specs/Benchmarks/Benchmarks.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Add_additional_files.cs
Labels: enhancement

#234 Resolve project file from additional files if possible
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
Labels: enhancement

#232 Make MsBuildProjectFileAnalyzer.ApplicableTo public
  specs/DotNetProjectFile.Analyzers.Specs/Rules/All.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build.ApplicableTo.cs
  specs/DotNetProjectFile.Analyzers.Specs/TestTools/Analyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidGeneratePackageOnBuildWhenNotPackable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionIncludeShouldExist.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ConfigureCentralPackageVersionManagement.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineIsPackable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineIsPublishable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineOutputType.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageValidationBaselineVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableCentralPackageManagementCentrally.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnablePackageValidation.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeDirectoryPackagesProps.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeProjectReferencesOnce.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProvideCompliantPackageIcon.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ReassignPropertiesWithDifferentValue.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseDirectoryPackagesPropsOnlyForCPM.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseDotNetAnalyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInCSharpContextOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInVBContextOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/VersionOverrideShouldChangeVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs
Labels: enhancement

#239 Update packages
  specs/Benchmarks/Benchmarks.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
Labels: enhancement

#241 Add packages to be included as private assets
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Labels: FN

#243 Add packages to be included as private assets part 2
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Labels: FN

#242 Proj0243: Generate SBOM
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  projects/PackageWithSBOMDisabled/PackageWithSBOMDisabled.csproj
  projects/PackageWithoutSBOM/PackageWithoutSBOM.csproj
  projects/PackageWithoutSBOMReference/PackageWithoutSBOMReference.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_package_validation.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_SBOM.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GenerateSbom.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/GenerateSBOM.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
  src/DotNetProjectFile.Analyzers/NuGet/BuildExtension.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#238 Proj4000: Report INI syntax errors
  dictionary.dic
  projects/IniSyntaxErrors/.editorconfig
  projects/IniSyntaxErrors/IniSyntaxErrors.csproj
  specs/Benchmarks/Program.cs
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/DiagnosticsAssertions.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/FindsExtensions.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/Issue.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/_should.cs
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/INI/INI_syntax.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Ini/IniSyntaxAnalyzer.cs
  src/DotNetProjectFile.Analyzers/Analyzers/IniFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/Category.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs
  src/DotNetProjectFile.Analyzers/Ini/HeaderSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/IniFile.cs
  src/DotNetProjectFile.Analyzers/Ini/IniFileSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/KeyValuePairSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/SectionSyntax.cs
  src/DotNetProjectFile.Analyzers/Ini/_grammar.cs
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/Parsing/Grammar.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/AddSyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/And.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/EndOfFile.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Or.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Repeat.cs
  src/DotNetProjectFile.Analyzers/Parsing/Parser.cs
  src/DotNetProjectFile.Analyzers/Properties/GlobalUsings.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.Ini.cs
  src/DotNetProjectFile.Analyzers/Rule.cs
  src/DotNetProjectFile.Analyzers/Syntax/SourceSpan.cs
  src/DotNetProjectFile.Analyzers/Syntax/SourceSpanLogger.cs
  src/DotNetProjectFile.Analyzers/Syntax/SourceSpanToken.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
Labels: New rule

#247 Fix INI syntax error and update INI key-value rule 4010
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/INI/INI_syntax.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Ini/HeaderSyntax.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.Ini.cs
Labels: documentation, enhancement

#246 Proj4050: Header must be a GLOB
  README.md
  projects/InvalidEditorConfigHeaders/.editorconfig
  projects/InvalidEditorConfigHeaders/InvalidEditorConfigHeaders.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/DiagnosticsAssertions.cs
  specs/DotNetProjectFile.Analyzers.Specs/IO/Glob_parse_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/EditorConfig/Header_must_be_glob.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
  src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/HeaderMustBeGlob.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/IO/Globbing/GlobParser.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.Ini.cs
Labels: New rule

#248 Proj4051: Use equals sign for key-value assignments
  projects/InvalidEditorConfigHeaders/.editorconfig
  specs/DotNetProjectFile.Analyzers.Specs/Rules/EditorConfig/Use_equals_for_assignment.cs
  src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/UseEqualsAssign.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.Ini.cs
Labels: New rule

#252 Fix crashing INI parsing
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/Examples/bug_00251.ini
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
  specs/DotNetProjectFile.Analyzers.Specs/TestTools/Source.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Grammr/Text/InvalidPattern.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpan.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpanLogger.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpanToken.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/GlobParser.cs
  src/DotNetProjectFile.Analyzers/Ini/IniFileSyntax.cs
  src/DotNetProjectFile.Analyzers/Parsing/ParseBuffer.cs
  src/DotNetProjectFile.Analyzers/Parsing/Parser.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxNodeResolver.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
  src/DotNetProjectFile.Analyzers/Syntax/Unparsable.cs
Labels: bug
