Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2025-02, with the labels that each got.

#305 Report on RESX files that are not added as additional files
  projects/CompliantCSharp/Messages.nl.resx
  projects/CompliantCSharp/Messages.resx
  projects/CompliantCSharpPackage/Messages.nl.resx
  projects/CompliantCSharpPackage/Messages.resx
  projects/ResxUnsorted/ResxUnsorted.csproj
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs
Labels: FN

#306 Proj0006: Report on RESX files that are not added as additional files
  README.md
  projects/CompliantCSharp/CompliantCSharp.csproj
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Add_additional_files.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/AddAdditionalFile.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: FN

#310 Publish packages in pipeline
  .github/workflows/build-test.yaml
Labels: enhancement

#312 Proj1001: Take <GlobalPackageReference>'s also into account
  specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_analyzers_for_packages.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableApiCompatibilityAttributeChecks.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs
Labels: FP

#313 Publish v1.5.8
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#309 Rules about global package references
  projects/UseCPM/Directory.Packages.props
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_global package_reference_only_in_Directory_Packages_props.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Global_package_references_are_meant_fo_private_assets_only.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineGlobalPackageReferenceInDirectoryPackagesOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileTypes.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#317 Implement the NuSpec file
  specs/DotNetProjectFile.Analyzers.Specs/NuGet/Nuspec_file_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/TestTools/Streams.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/Metadata.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuSpecFile.cs
Labels: enhancement

#316 Proj0809 Use nuget cache for information about dependency type
  projects/GlobalPackageReferenceRuntimeDependency/Directory.Packages.props
  projects/GlobalPackageReferenceRuntimeDependency/GlobalPackageReferenceRuntimeDependency.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Global_package_references_are_meant_fo_private_assets_only.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/IO/IODirectory.cs
  src/DotNetProjectFile.Analyzers/IO/IOFile.cs
  src/DotNetProjectFile.Analyzers/IO/IOPath.cs
  src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
Labels: FN

#331 Proj0034: Import statement could not be resolved
  projects/UnresolvableImport/UnresolvableImport.csproj
  projects/UnresolvableImport/common.props
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Unresolvable_Import.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/UnresolvableImport.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#332 Disable rules that can not be excecuted correctly on a failing import
  projects/UnresolvableImport/UnresolvableImport.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Unresolvable_Import.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AdoptPreferredCasing.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidCompileItemInSdk.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidLicenseUrl.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidUsingMoq.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionIncludeShouldExist.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionsShouldHaveSingleTask.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineConditionsOnLevel1.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineGlobalPackageReferenceInDirectoryPackagesOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceAssetsAsAttributes.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineUsingsExplicit.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GeneratePackageOnBuildConditionally.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IndentXml.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ItemGroupShouldBeUniform.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/MigrateAwayFromBinaryFormatter.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/MigrateFromRulesetToEditorConfigFile.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageReferencesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageVersionsAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderProjectReferencesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesByType.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProjectReferenceIncludeShouldExist.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProvideCompliantPackageIcon.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveEmptyNodes.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveFolderNodes.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveIncludeAssetsWhenRedundant.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/StaticAliasUsingNotSupported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TrackToDoTags.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UnresolvableImport.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseForwardSlashesInPaths.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
Labels: FP

#325 Use cache for dependency types
  specs/DotNetProjectFile.Analyzers.Specs/NuGet/Nuspec_file_specs.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.Linq.Enumerable.cs
  src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageInfo.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/Metadata.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/MetadataLicense.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuSpecFile.cs
Labels: FN

#333 Introduction of `GetMsBuildProperty()`
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions.cs
  src/DotNetProjectFile.Analyzers/build/DotNetProjectFile.Analyzers.props
Labels: enhancement

#334 Introduction of PackageReferenceBase
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GenerateSbom.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/MsBuild/GlobalPackageReference.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReferenceBase.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageVersion.cs
  src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs
  src/DotNetProjectFile.Analyzers/NuGet/Package.cs
Labels: enhancement

#336 Proj0502: Package contains an incompatible license
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Licensing/Only_include_packages_with_explicit_license.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Licensing/Package_only_contains_deprecated_license_URL.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Thrid_Party_license_compliance.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Licensing/LicenseExpression.cs
  src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs
  src/DotNetProjectFile.Analyzers/Licensing/UnknownLicense.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
  src/DotNetProjectFile.Analyzers/build/DotNetProjectFile.Analyzers.props
Labels: New rule

#348 Investigate non-reproducable issue
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Exclude_private_asset_dependencies.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
Labels: invalid

#351 Proj1103 and Proj1104 about TUnit usage
  projects/TUnitTestProject/TUnitTestProject.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/TUnit_usage.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TUnitUsage.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#353 Proj0035: Remove deprecated RestoreProjectStyle property
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_deprecated_RestoreProjectStyle.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveDeprecatedRestoreProjectStyle.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/RestoreProjectStyle.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#352 Support more (common) license types
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/Compatibility_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/0BSD.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/AGPL-1.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/AGPL-1.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/AGPL-3.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/AGPL-3.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/Apache-1.0.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/Apache-1.1.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/Apache-2.0.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/BSD-1-Clause.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/BSD-2-Clause.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/BSD-3-Clause.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/BSD-4-Clause.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/EPL-1.0.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/EPL-2.0.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/GPL-1.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/GPL-1.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/GPL-2.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/GPL-2.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/GPL-3.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/GPL-3.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/LGPL-2.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/LGPL-2.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/LGPL-3.0-only.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/LGPL-3.0-or-later.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MIT.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MPL-1.0.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MPL-1.1.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MPL-2.0-no-copyleft-exception.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MPL-2.0.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MS-LPL.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/MS-PL.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/PostgreSQL.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/Unlicense.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Generated/WTFPL.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Manual/NET_Library_EULA_ENU.txt
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/Spdx_generator.cs
  src/DotNetProjectFile.Analyzers/Licensing/AndLicenseExpression.cs
  src/DotNetProjectFile.Analyzers/Licensing/CopyLeftLicense.cs
  src/DotNetProjectFile.Analyzers/Licensing/Generated/spdx_info.bin
  src/DotNetProjectFile.Analyzers/Licensing/LicenseExpression.cs
  src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs
  src/DotNetProjectFile.Analyzers/Licensing/OrLicenseExpression.cs
  src/DotNetProjectFile.Analyzers/Licensing/PermissiveLicense.cs
  src/DotNetProjectFile.Analyzers/Licensing/PropietaryLicense.cs
  src/DotNetProjectFile.Analyzers/Licensing/SingleLicense.cs
  src/DotNetProjectFile.Analyzers/Licensing/UnknownLicense.cs
Labels: enhancement

#354 Proj0810: Remove unused package versions
  .net.csproj
  projects/CPMWithUnusedPackageVersions/.net.csproj
  projects/CPMWithUnusedPackageVersions/CPMWithUnusedPackageVersions.csproj
  projects/CPMWithUnusedPackageVersions/Directory.Packages.props
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Remove_unused_package_versions.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveUnusedPackageVersions.cs
  src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileType.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileTypes.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
  src/DotNetProjectFile.Analyzers/build/DotNetProjectFile.Analyzers.props
Labels: New rule

#357 Violating RS1035 is no concern in a specs project
  specs/DotNetProjectFile.Analyzers.Specs/.globalconfig
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/Spdx_generator.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Thrid_Party_license_compliance.cs
Labels: enhancement

#362 Introduction of custom license
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Thrid_Party_license_compliance.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/Licensing/CustomLicense.cs
  src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs
Labels: enhancement

#365 Proj1003: Take <GlobalPackageReference>s also into account
  projects/SonarCS/SonarCS.csproj
  projects/SonarVB/SonarVB.vbproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_Sonar_analyzers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: FP

#368 Use AwesomeAssertions
  projects/DotnetProjectFilesSdk/.net.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/DiagnosticAnalyzerAssertions.cs
  specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/DiagnosticsAssertions.cs
Labels: enhancement

#363 Resolve nuget.config globalPackagesFolder
  specs/DotNetProjectFile.Analyzers.Specs/NuGet/NuGet_config_file_specs.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuGetConfigFile.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuGetConfigKeyValue.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuGetConfigSection.cs
Labels: enhancement

#369 Resolve dependencies Nuspec file
  specs/DotNetProjectFile.Analyzers.Specs/NuGet/Nuspec_file_specs.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/Metadata.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuSpecFile.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuspecDepedencies.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuspecDependency.cs
Labels: enhancement

#370 Support mit-license.org
  specs/Benchmarks/Licening.cs
  specs/Benchmarks/Program.cs
  specs/Benchmarks/README.md
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/Url_specs.cs
  src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs
Labels: enhancement, FP

#372 Proj3002: Remove commented-out code
  projects/ResxCommentedOut/Resources.resx
  projects/ResxCommentedOut/ResxCommentedOut.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/Generic/Remove_commented_out_code.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/Helpers/CommentChecker_specs.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/CommentChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveCommentedOutCode.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/RemoveCommentedOutCode.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#377 Proj0036: Remove None when redundant
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_None_when_redundant.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveNoneWhenRedundant.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#380 Implement glob match
  specs/Benchmarks/Globs.cs
  specs/Benchmarks/Program.cs
  specs/DotNetProjectFile.Analyzers.Specs/IO/Glob_parse_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Text/Glob_parse_specs.cs
  src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/HeaderMustBeGlob.cs
  src/DotNetProjectFile.Analyzers/Conversion/GlobTypeConverter.cs
  src/DotNetProjectFile.Analyzers/Extensions/System.Collections.Generic.IReadOnlyList.cs
  src/DotNetProjectFile.Analyzers/Git/PatternSyntax.cs
  src/DotNetProjectFile.Analyzers/IO/Glob.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/AnyChar.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Group.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Literal.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/NotSequense.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Option.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/RecursiveWildcard.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Segement.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Sequence.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/Wildcard.cs
  src/DotNetProjectFile.Analyzers/Text/Glob.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/AnyChar.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/GlobParser.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/Group.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/Literal.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/NotSequense.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/Option.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/RecursiveWildcard.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/Segment.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/Sequence.cs
  src/DotNetProjectFile.Analyzers/Text/Globbing/Wildcard.cs
Labels: enhancement

#379 Deal with custom third-party licenses
  props/common.props
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Thrid_Party_license_compliance.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/ThirdPartyLicense.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#386 Rules to validate <ThirdPartyLicense>
  README.md
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/ThirdPartyLicensence_compliance.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseCompliance.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Licensing/CustomLicense.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule
