Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2025-03, with the labels that each got.

#389 Proj0214: Severity as INFO as it is considered too opinionated
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: enhancement

#390 Proj1701: Do not report on short (less then 3 lines) release notes
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_CDATA_for_large_texts.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: FP

#395 Add dotnet as extra search tag
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveCommentedOutCode.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/RemoveCommentedOutCode.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: documentation, enhancement

#397 Change suggested analyzer logic to use packagereferences rather than assembly names
  projects/PackagesWithoutAnalyzers/PackagesWithoutAnalyzers.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_analyzers_for_packages.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReferenceBase.cs
  src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs
  src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Labels: FN

#396 Proj0037: Exclude compile when all assets are private
  .net.csproj
  projects/BloatedDirectoryPackagesProps/Directory.Packages.props
  projects/CPMWithUnusedPackageVersions/.net.csproj
  projects/CompliantCSharp/CompliantCSharp.csproj
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  projects/DotnetProjectFilesSdk/.net.csproj
  projects/ImplicitPackablePublishableTestProject/ImplicitPackablePublishableTestProject.csproj
  projects/IncludeAssets/IncludeAssets.csproj
  projects/NoPackageRequireLicenseAcceptance/NoPackageRequireLicenseAcceptance.csproj
  projects/PackablePublishableTestProject/PackablePublishableTestProject.csproj
  projects/PackageReferenceWithoutVersion/common.props
  projects/PackageRequireLicenseAcceptanceDisabled/PackageRequireLicenseAcceptanceDisabled.csproj
  projects/PackagesWithAnalyzers/PackagesWithAnalyzers.csproj
  projects/SdkWithCompileItems/.net.csproj
  projects/SonarCS/SonarCS.csproj
  projects/SuppressIssues/SuppressIssues.csproj
  projects/TUnitTestProject/TUnitTestProject.csproj
  projects/TestProject/TestProject.csproj
  projects/TestSdkOnly/TestSdkOnly.csproj
  projects/UnstablePackageReferences/UnstablePackageReferences.csproj
  projects/UnstableVersionsCPM/UnstableVersionsCPM.csproj
  props/common.props
  specs/Benchmarks/Benchmarks.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Exclude_compile_when_all_assets_are_private.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_IncludeAssets_when_redundant.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ValidatePrivateAssets.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#399 Report issues on root node only on start element
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_api_compatibility_attribute_checks.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_api_compatibility_parameter_name_checks.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_baseline_validation.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_framework_validation.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_SBOM.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_api_compatibility_suppression_file.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_documentation_file.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Require_SDK.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_packable.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_publishable.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/TUnit_usage.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#400 Simplify naming and types
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PackageReferenceBase.cs
  src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs
  src/DotNetProjectFile.Analyzers/NuGet/BuildExtension.cs
  src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs
  src/DotNetProjectFile.Analyzers/NuGet/Package.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageVersionInfo.cs
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
  src/DotNetProjectFile.Analyzers/NuGet/SourceGenerator.cs
Labels: enhancement

#409 Use .Children<> instead of SelectMany
  projects/TargetFrameworksSingleWithBase/common.props
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/File_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Choose_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_global package_reference_only_in_Directory_Packages_props.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_properties_once.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidCompileItemInSdk.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidLicenseUrl.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidUsingMoq.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionsShouldHaveSingleTask.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineGlobalPackageReferenceInDirectoryPackagesOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceAssetsAsAttributes.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePropertiesOnce.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineSingleTargetFramework.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineUsingsExplicit.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableCentralPackageManagementCentrally.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GeneratePackageOnBuildConditionally.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/MigrateAwayFromBinaryFormatter.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/MigrateFromRulesetToEditorConfigFile.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageReferencesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OverrideTargetFrameworksWithTargetFrameworks.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveDeprecatedRestoreProjectStyle.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveFolderNodes.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveNoneWhenRedundant.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveUnusedPackageVersions.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/StaticAliasUsingNotSupported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectShouldNotBePackable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectShouldNotBePublishable.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseCompliance.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseVersionOnlyWithoutCpm.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseVersionOverrideOnlyWithCpm.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ValidatePrivateAssets.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/VersionOverrideShouldChangeVersion.cs
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
  src/DotNetProjectFile.Analyzers/Xml/Nodes.T.cs
Labels: enhancement

#408 Proj0038: Specify NoWarn rule IDs fully
  globalconfig.verified.txt
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Fully_specify_NoWarn_rule_IDs.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/FullySpecifyNoWarnRuleIds.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/System.Linq.Enumerable.cs
  src/DotNetProjectFile.Analyzers/MsBuild/NoWarn.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#410 Proj0026: Stop reporting on conditonal properties
  projects/Conditional/Conditional.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_conditions_on_level_1.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineConditionsOnLevel1.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: FP

#413 Fix missing package names in warnings when reference is an update instead of include
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceAssetsAsAttributes.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveUnusedPackageVersions.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: bug

#415 Adopt SLNX project file format
  .editorconfig
  .github/workflows/build-test.yaml
  dotnet-project-file-analyzers.sln
  dotnet-project-file-analyzers.slnx
Labels: enhancement

#417 Proj0039: Treat all warnings as errors is considered a bad practice
  globalconfig.verified.txt
  projects/ProjectReferenceMissingInclude/ProjectReferenceMissingInclude.csproj
  specs/Benchmarks/Benchmarks.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Manual/NET_Library_EULA_ENU/web_without_french.txt
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/ThirdPartyLicensence_compliance.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Treat_warnings_as_warnings.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TreatWarningsAsWarnings.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/TreatWarningsAsErrors.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule
