Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2025-01, with the labels that each got.

#259 Prevent NU1504 from being raised when Directory.Packages.props is used
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
Labels: bug

#261 Proj0009: Take conditionals into account
  projects/TargetFrameworkOverridesConditional/TargetFrameworkOverridesConditional.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Override_TargetFrameworks_with_TargetFrameworks.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OverrideTargetFrameworksWithTargetFrameworks.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: FP

#262 Proj0033: Track uses of ""TODO"" tags
  projects/ToDo/ToDo.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Track_TODO_tags.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/ToDoChecker_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/XML/XML_positions.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/ToDoChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TrackToDoTags.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/Category.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlComment.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs
Labels: New rule

#263 Move argument of IdentationChecker
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IndentXml.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/IndentResx.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: enhancement

#264 Implement Track TODO tags for RESX
  projects/ToDo/Resources.resx
  projects/ToDo/ToDo.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Track_TODO_tags.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Resx/TrackToDoTags.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Resx/Comment.cs
  src/DotNetProjectFile.Analyzers/Resx/Node.Create.cs
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#268 Fix error reporting in wrong files
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Include_package_references_once.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Track_TODO_tags.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/HeaderMustBeGlob.cs
  src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/UseEqualsAssign.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/ToDoChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Ini/EmptySection.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ConfigureCentralPackageVersionManagement.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeDirectoryPackagesProps.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/Resx/Node.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlComment.cs
Labels: bug

#271 Introduction of XML Locations
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Configure_CPM.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Include_Directory_Packages_props.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Ommit_XML_declaration.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_CDATA_for_large_texts.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/Helpers/ToDoChecker.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ConfigureCentralPackageVersionManagement.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeDirectoryPackagesProps.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs
  src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
  src/DotNetProjectFile.Analyzers/Resx/Node.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlComment.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlLocations.cs
  src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs
Labels: enhancement

#273 Added AppendOnlyCollection to improve performance of parsing
  props/common.props
  specs/DotNetProjectFile.Analyzers.Specs/Collections/AppendOnlyCollection_specs.cs
  src/DotNetProjectFile.Analyzers/Collections/AppendOnlyCollection.cs
  src/DotNetProjectFile.Analyzers/Collections/Enumerator.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#274 Refactor source span
  specs/DotNetProjectFile.Analyzers.Specs/Grammr/Text/SourceSpan_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Parsing/Grammar_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/TestTools/Source.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/InvalidPattern.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/Source.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpan.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpanToken.cs
  src/DotNetProjectFile.Analyzers/IO/Globbing/GlobParser.cs
  src/DotNetProjectFile.Analyzers/Parsing/Grammar.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/Matches.cs
  src/DotNetProjectFile.Analyzers/Parsing/Internal/RegularExpression.cs
  src/DotNetProjectFile.Analyzers/Parsing/Parser.cs
  src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
Labels: enhancement

#278 Fix incorrect parsing of Using node's Static property
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/Using.cs
Labels: bug

#280 Remove UTF-8 BOM from test project files
  projects/BloatedDirectoryPackagesProps/BloatedDirectoryPackagesProps.csproj
  projects/ChooseWhen/ChooseWhen.csproj
  projects/CompliantVB/CompliantVB.vbproj
  projects/CompliantVB/Messages.nl.resx
  projects/CompliantVB/Messages.resx
  projects/CompliantVBPackage/Messages.nl.resx
  projects/CompliantVBPackage/Messages.resx
  projects/Conditional/Conditional.csproj
  projects/DoublePackageReferences/DoublePackageReferences.csproj
  projects/DoubleProjectReferences/DoubleProjectReferences.csproj
  projects/EmptyInclude/EmptyInclude.csproj
  projects/EnableCPMLocally/EnableCPMLocally.csproj
  projects/FaultyIndenting/FaultyIndenting.resx
  projects/ImplicitPackablePublishableTestProject/ImplicitPackablePublishableTestProject.csproj
  projects/ImplicitUsings/ImplicitUsings.csproj
  projects/IncludeAssets/IncludeAssets.csproj
  projects/IncorrectlyOrderedUsingDirectives/IncorrectlyOrderedUsingDirectives.csproj
  projects/LegacyProject/LegacyProject.csproj
  projects/MisuseVersion/MisuseVersion.csproj
  projects/MisuseVersionOverride/MisuseVersionOverride.csproj
  projects/MultipleBuildActionTasks/MultipleBuildActionTasks.csproj
  projects/MultipleBuildActionTasks/README.md
  projects/PackablePublishableTestProject/PackablePublishableTestProject.csproj
  projects/PackageReferenceAssetsAsAttributes/PackageReferenceAssetsAsAttributes.csproj
  projects/PackageReferenceAssetsAsElements/PackageReferenceAssetsAsElements.csproj
  projects/PackageReferenceWithoutVersion/PackageReferenceWithoutVersion.csproj
  projects/PackagesWithAnalyzers/PackagesWithAnalyzers.csproj
  projects/PackagesWithoutAnalyzers/PackagesWithoutAnalyzers.csproj
  projects/PrivateAssets/PrivateAssets.csproj
  projects/ResxMissingInvariant/Chess.de-AT.resx
  projects/ResxMissingInvariant/Chess.nl.resx
  projects/ResxMissingInvariant/Chess.resx
  projects/ResxNoData/Resources.resx
  projects/ResxNoHeaders/Resources.resx
  projects/ResxNoInvariant/Resources.nl.resx
  projects/ResxNoXml/Resources.resx
  projects/ResxUnsorted/Resources.resx
  projects/ResxWithHtmlContent/Messages.resx
  projects/TargetFrameworksSingleWithBase/TargetFrameworksSingleWithBase.csproj
  projects/TestProject/TestProject.csproj
  projects/TestProjectWithoutSdk/TestProjectWithoutSdk.csproj
  projects/TestSdkOnly/TestSdkOnly.csproj
  projects/UnstablePackageReferences/UnstablePackageReferences.csproj
  projects/UsesMoq/UsesMoq.csproj
  projects/WithDirectoryBuildProps/Directory.Build.props
  projects/WithDirectoryBuildProps/Directory.Build.targets
  projects/WithDirectoryBuildProps/WithDirectoryBuildProps.csproj
  projects/WithRuleset/WithRuleset.csproj
  src/DotNetProjectFile.Analyzers.Sdk/README.md
Labels: enhancement

#277 Proj0244: Generate documentation file
  projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
  projects/GenerateDocumentationFileDisabledWithFile/GenerateDocumentationFileDisabledWithFile.csproj
  projects/GenerateDocumentationFileDisabledWithoutFile/GenerateDocumentationFileDisabledWithoutFile.csproj
  projects/GenerateDocumentationFileEnabled/GenerateDocumentationFileEnabled.csproj
  projects/GenerateDocumentationFileEnabledWithFile/GenerateDocumentationFileEnabledWithFile.csproj
  projects/GenerateDocumentationFileMissing/GenerateDocumentationFileMissing.csproj
  projects/GenerateDocumentationFileMissingWithEmptyFile/GenerateDocumentationFileMissingWithEmptyFile.csproj
  projects/GenerateDocumentationFileMissingWithFile/GenerateDocumentationFileMissingWithFile.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_documentation_file.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableGenerateDocumentationFile.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/DocumentationFile.cs
  src/DotNetProjectFile.Analyzers/MsBuild/GenerateDocumentationFile.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#276 Proj0033: Project reference includes should exist
  projects/ProjectReferenceMissingInclude/ProjectReferenceMissingInclude.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Project_reference_include_should_exist.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ProjectReferenceIncludeShouldExist.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#281 Fix changelog error
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: documentation

#286 Fix broken ``have_mark_down_documentation` tests
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
Labels: bug, documentation

#283 Proj0245 & Proj0246 VersionPrefix/Suffix Rules
  projects/VersionPrefix/VersionPrefix.csproj
  projects/VersionPrefixAndSuffix/VersionPrefixAndSuffix.csproj
  projects/VersionPrefixAndSuffixAndVersion/VersionPrefixAndSuffixAndVersion.csproj
  projects/VersionPrefixAndVersion/VersionPrefixAndVersion.csproj
  projects/VersionSuffix/VersionSuffix.csproj
  projects/VersionSuffixAndVersion/VersionSuffixAndVersion.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_version_prefix_if_version_suffix_is_defined.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Dont_mix_version_and_version_prefix_or_version_suffix.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Define_package_info.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineVersionPrefixIfVersionSuffixIsDefined.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DontMixVersionAndVersionPrefixOrVersionSuffix.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/VersionPrefix.cs
  src/DotNetProjectFile.Analyzers/MsBuild/VersionSuffix.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule, FP

#284 Introduction Grammr parser
  dictionary.dic
  specs/Benchmarks/GrammrParsing.cs
  specs/Benchmarks/Program.cs
  specs/DotNetProjectFile.Analyzers.Specs/Collections/AppendOnlyList_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Grammr/Lexers_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Grammr/Parsers_specs.cs
  specs/DotNetProjectFile.Analyzers.Specs/Grammr/ResultQueue_specs.cs
  src/DotNetProjectFile.Analyzers/Collections/AppendOnlyList.cs
  src/DotNetProjectFile.Analyzers/Collections/Enumerator.cs
  src/DotNetProjectFile.Analyzers/Collections/Slice.cs
  src/DotNetProjectFile.Analyzers/Grammr/Grammar.cs
  src/DotNetProjectFile.Analyzers/Grammr/Lexers/Char.cs
  src/DotNetProjectFile.Analyzers/Grammr/Lexers/EndOfFile.cs
  src/DotNetProjectFile.Analyzers/Grammr/Lexers/EndOfLine.cs
  src/DotNetProjectFile.Analyzers/Grammr/Lexers/Predicate.cs
  src/DotNetProjectFile.Analyzers/Grammr/Lexers/RegularExpression.cs
  src/DotNetProjectFile.Analyzers/Grammr/Lexers/String.cs
  src/DotNetProjectFile.Analyzers/Grammr/Parser.cs
  src/DotNetProjectFile.Analyzers/Grammr/Parsers/Repeat.cs
  src/DotNetProjectFile.Analyzers/Grammr/Parsers/Sequence.cs
  src/DotNetProjectFile.Analyzers/Grammr/Parsers/Switch.cs
  src/DotNetProjectFile.Analyzers/Grammr/Parsers/Typed.cs
  src/DotNetProjectFile.Analyzers/Grammr/README.md
  src/DotNetProjectFile.Analyzers/Grammr/Result.cs
  src/DotNetProjectFile.Analyzers/Grammr/ResultQueue.cs
  src/DotNetProjectFile.Analyzers/Grammr/Syntax/Node.cs
  src/DotNetProjectFile.Analyzers/Grammr/Syntax/Nodes.cs
  src/DotNetProjectFile.Analyzers/Grammr/Syntax/Tree.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpanLogger.cs
  src/DotNetProjectFile.Analyzers/Grammr/Text/TokenStream.cs
  src/DotNetProjectFile.Analyzers/Grammr/Token.cs
Labels: enhancement

#293 Fix TUnit related false positives
  projects/TUnitTestProject/TUnitTestProject.csproj
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Require_SDK.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Labels: FP

#301 Release v1.5.6
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.targets
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement
