Repository dotnet-project-file-analyzers/dotnet-project-file-analyzers, pull requests merged in 2025-06, with the labels that each got.

#449 Proj0044 Allow CI conditionals
  specs/DotNetProjectFile.Analyzers.Specs/Properties/GlobalUsings.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_continuous_integration_build.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_restore_locked_mode.cs
  specs/DotNetProjectFile.Analyzers.Specs/TestTools/BuildAgentHelpers.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableContinuousIntegrationBuild.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableRestoreLockedMode.cs
  src/DotNetProjectFile.Analyzers/BuildAgents/BuildAgent.cs
  src/DotNetProjectFile.Analyzers/Caching/EnumCache.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.MsBuild.Node.cs
Labels: enhancement, FP

#451 Proj0508: Order third-party licenses alphabetically
  globalconfig.verified.txt
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Order_third_party_licenses_in_alphabetical_order.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderThirdPartyLicensesAlphabetically.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#457 Verify third-party licenses on package info
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Third_Party_license_compliance.cs
  src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/MsBuild/ThirdPartyLicense.cs
  src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
Labels: bug, FP

#464 Fix Proj0240 message incorrectly suggesting to disable DevelopmentDependency, rather than to enable it
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_package_validation.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: bug

#438 Create and publish release on git tag
  .github/workflows/build-publish.yml
  .github/workflows/build-test.yaml
Labels: enhancement

#470 Analysis on project files are not longer executed for the SDK
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Labels: enhancement

#474 Add .net.csproj SDK example
  .net.csproj
  README.md
  docs/general/.net.csproj
  docs/general/sdk.md
  specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
Labels: documentation

#480 Proj0046: Update statements should change state
  docs/README.md
  docs/rules/Proj0046.md
  globalconfig.verified.txt
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Update_should_change_state.cs
  src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UpdateShouldChangeState.cs
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/README.md
  src/DotNetProjectFile.Analyzers/Rule.cs
Labels: New rule

#481 Add testcase for assumed FP
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Global_package_references_are_meant_fo_private_assets_only.cs
  specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_IncludeAssets_when_redundant.cs
Labels: enhancement

#482 Bump versions
  props/common.props
  specs/Benchmarks/Benchmarks.csproj
  specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
  src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
  src/DotNetProjectFile.Analyzers/packages.lock.json
Labels: enhancement
